# Generated by Django 4.1.3 on 2022-11-09 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0004_rename_book_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='books',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Available'), (2, 'Checked_out'), (3, 'Damaged'), (4, 'Lost')], default=1),
        ),
    ]
