# Generated by Django 4.1.3 on 2022-11-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_books_checked_out_by_alter_books_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post',
            new_name='book',
        ),
        migrations.AlterField(
            model_name='books',
            name='location',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Exactus Office'), (2, "Owner's Home"), (3, 'In the Matrix')], default=1),
        ),
    ]
