# Generated by Django 4.1.3 on 2022-11-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_books_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Available'), (2, 'Checked Out'), (3, 'Damaged'), (4, 'Lost')], default=1),
        ),
    ]
