# Generated by Django 4.1.3 on 2022-11-16 16:20

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('books', '0009_alter_books_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
