# Generated by Django 4.1.3 on 2022-11-16 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_books_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='tags',
            new_name='author_tags',
        ),
    ]
