# Generated by Django 4.1.3 on 2022-11-16 17:55

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('books', '0011_rename_tags_books_author_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedAuthors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='books',
            name='author_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='books.TaggedAuthors', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
