# Generated by Django 4.1.3 on 2022-11-16 18:04

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('books', '0012_taggedauthors_alter_books_author_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='TaggedAuthors',
        ),
    ]
