# Generated by Django 4.1.3 on 2022-11-16 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_books_author_tags_delete_taggedauthors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='author_tags',
            new_name='tags',
        ),
    ]
