# Generated by Django 4.1.3 on 2022-11-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_books_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='books',
            name='tags',
        ),
        migrations.AddField(
            model_name='books',
            name='author_tags',
            field=models.ManyToManyField(blank=True, null=True, to='books.authors'),
        ),
    ]
